In [14]:
import numpy as np
x = np.arange(15)
x.shape = (3,5)
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
x[0:-1]  # Think of this as though it's an array of arrays. This only prints indices 0,1,2,..., maxIndex-1, or [0:(2-1)] = [0:1]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x[1:-1] # Same as x[1:maxIndex-1] = x[1:(2-1)] = x[1:1].  Array starting with 5

array([[5, 6, 7, 8, 9]])

In [20]:
y=[1,2]